### PR TITLE
fix(logs): respect TZ env var for timestamp display, fix Windows timezone

### LINKED ISSUE #21606: [Bug]: OpenClaw logs ignore TZ environment variable, always show UTC time on Windows
### Summary

Even after setting TZ=Asia/Shanghai environment variable and upgrading to latest version (2026.2.19), OpenClaw logs still display UTC time instead of local time.

### Steps to reproduce

1. Set environment variable: TZ=Asia/Shanghai
2. Start OpenClaw: openclaw gateway start
3. Check logs: openclaw logs
4. Observe time is in UTC (e.g., shows 04:18 when local time is 12:18)

### Expected behavior

Logs should display local time according to TZ environment variable.

### Actual behavior

Logs always show UTC time regardless of TZ setting.

### OpenClaw version

2026.2.19

### Operating system

Win11

### Install method

npm install -g openclaw@latest

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

_No response_

### Additional information

- C:\Users\86137>node -v
   v24.13.0
- Timezone: Asia/Shanghai (GMT+8)
- Tried both system environment variable and set TZ=Asia/Shanghai before command
- Issue persists after upgrade from 2026.2.9 to 2026.2.19
- Discord and other functions work fine, only time display is affected

### PR DESCRIPTION
**Pull request by hydro13**
## Summary

`openclaw logs` always displayed UTC timestamps regardless of the `TZ` environment variable. On Windows especially, Node.js does not reliably read `TZ` to adjust `getHours()` / `getTimezoneOffset()` — the methods used by the old implementation.

## Root Cause

`formatLocalIsoWithOffset()` in `src/logging/timestamps.ts` manually assembled a timestamp using `getHours()`, `getMinutes()`, `getTimezoneOffset()` etc. These methods read the process timezone from the OS — which on Windows does not pick up the `TZ` environment variable set by the user.

### 1. `src/logging/timestamps.ts` — rewrite using `Intl.DateTimeFormat`

Replace the old manual approach with `Intl.DateTimeFormat` using an explicit `timeZone` parameter. `Intl` correctly resolves timezone conversions on all platforms including Windows.

- Function now accepts an optional `timeZone` argument, falling back to `process.env.TZ`, then `Intl.DateTimeFormat().resolvedOptions().timeZone`
- Added `parseGmtOffset()` helper to normalize `"GMT+8"` → `"+08:00"` format

### 2. `src/cli/logs-cli.ts` — auto-enable local time when `TZ` is set

```typescript
// Before
const localTime = Boolean(opts.localTime);

// After
const localTime = Boolean(opts.localTime) || Boolean(process.env.TZ);
```

Users who set `TZ=Asia/Shanghai` now see local timestamps automatically without needing `--local-time`.

## Tests

6 tests in `src/logging/timestamps.test.ts`:

| Test | Result |
|---|---|
| UTC → `+00:00` offset | ✅ |
| `Asia/Shanghai` → `+08:00`, correct hour conversion | ✅ |
| `America/New_York` winter (EST) → `-05:00` | ✅ |
| `America/New_York` summer (EDT) → `-04:00` | ✅ |
| Output matches ISO 8601 with offset regex | ✅ |
| Source does NOT contain `getHours`, `getMinutes`, `getTimezoneOffset` | ✅ |

All 43 tests in `src/logging/` pass.

Fixes #21606

<h3>Greptile Summary</h3>

Replaced manual timezone offset calculation with `Intl.DateTimeFormat` to properly respect the `TZ` environment variable on all platforms, especially Windows. The implementation correctly uses `timeZone` parameter in `Intl.DateTimeFormat` which resolves timezone conversions reliably across platforms. The PR also auto-enables local time display when `TZ` is set in the environment.

<h3>Confidence Score: 5/5</h3>

- This PR is safe to merge with minimal risk
- The implementation is a well-tested refactoring that replaces platform-dependent Date methods with the standard `Intl.DateTimeFormat` API. All 6 new tests pass including timezone conversion validation, DST handling, and verification that legacy methods are no longer used. The change is backward compatible (optional parameter) and addresses a real cross-platform bug on Windows.
- No files require special attention

<sub>Last reviewed commit: b39bb3a</sub>

### CODE REVIEW

File: src/logging/timestamps.ts [hunk 1]
```diff
@@ -1,14 +1,48 @@
...
-  const m = String(now.getMinutes()).padStart(2, "0");
-  const s = String(now.getSeconds()).padStart(2, "0");
-  const ms = String(now.getMilliseconds()).padStart(3, "0");
-  const tzOffset = now.getTimezoneOffset();
-  const tzSign = tzOffset <= 0 ? "+" : "-";
-  const tzHours = String(Math.floor(Math.abs(tzOffset) / 60)).padStart(2, "0");
-  const tzMinutes = String(Math.abs(tzOffset) % 60).padStart(2, "0");
-  return `${year}-${month}-${day}T${h}:${m}:${s}.${ms}${tzSign}${tzHours}:${tzMinutes}`;
+export function formatLocalIsoWithOffset(now: Date, timeZone?: string): string {
+  const tz = timeZone ?? process.env.TZ ?? Intl.DateTimeFormat().resolvedOptions().timeZone;
```
Comment (HenryLoenwind) [inline src/logging/timestamps.ts]: env.TZ needs to be checked. What happens when someone runs `TZ="yo agent's" openclaw logs`?

File: src/cli/logs-cli.ts [hunk 2]
```diff
@@ -223,7 +223,7 @@ export function registerLogsCli(program: Command) {
     const jsonMode = Boolean(opts.json);
     const pretty = !jsonMode && Boolean(process.stdout.isTTY) && !opts.plain;
     const rich = isRich() && opts.color !== false;
-    const localTime = Boolean(opts.localTime);
+    const localTime = Boolean(opts.localTime) || Boolean(process.env.TZ);
```
Comment (HenryLoenwind) [inline src/cli/logs-cli.ts]: Again, existence is not enough, it needs to be usable.

File: src/logging/timestamps.ts [hunk 3]
```diff
@@ -1,14 +1,48 @@
...
+
+  // Use Intl.DateTimeFormat to get date/time parts in the target timezone
+  const fmt = new Intl.DateTimeFormat("en-CA", {
```
Comment (HenryLoenwind) [inline src/logging/timestamps.ts]: "en-CA"? Nothing against Canada, but...

File: src/logging/timestamps.ts [hunk 4]
```diff
@@ -1,14 +1,48 @@
...
+    minute: "2-digit",
+    second: "2-digit",
+    hour12: false,
+    fractionalSecondDigits: 3 as 1 | 2 | 3,
+  });
+
+  const partsMap = Object.fromEntries(fmt.formatToParts(now).map((p) => [p.type, p.value]));
+
+  // Get the UTC offset string for the target timezone
+  const offsetFmt = new Intl.DateTimeFormat("en", {
```
Comment (HenryLoenwind) [inline src/logging/timestamps.ts]: Can't those two calls be combined?

File: src/logging/timestamps.ts [hunk 5]
```diff
@@ -1,14 +1,48 @@
...
+    timeZone: tz,
+    timeZoneName: "shortOffset",
```
Comment (HenryLoenwind) [inline src/logging/timestamps.ts]: Just use longOffset and snip away the "GMT" at the beginning.

**Review by HenryLoenwind — CHANGES_REQUESTED** [review]

**Review by hydro13 — COMMENTED** [review]
Thanks for the thorough review! All 5 points addressed:

- Added `isValidTimeZone()` (try/catch Intl validation) — invalid `TZ` values like `"yo agent's"` now fall back to the system timezone instead of crashing or producing garbage
- `localTime` in `logs-cli.ts` now requires both truthiness **and** a valid timezone via `isValidTimeZone()`
- Locale changed from `"en-CA"` to `"en"`
- Merged both `Intl.DateTimeFormat` calls into one with `timeZoneName: "longOffset"` included
- `parseGmtOffset()` deleted — `longOffset` already produces zero-padded `"GMT+08:00"` format, so `.slice(3)` suffices (and `"GMT"` maps directly to `"+00:00"`)

**Review by HenryLoenwind — APPROVED** [review]
Looks good now. 👍

**Comment by hydro13** [comment]
Rebased on current main. Still relevant and ready for merge.
