### PR TITLE
fix(cron): stagger missed jobs on restart to prevent gateway overload

### LINKED ISSUE #18892: Gateway becomes unresponsive when restarted with overdue cron jobs
## Bug Description

When the gateway is restarted while multiple cron jobs have `nextRunAtMs` values in the past (i.e., they were scheduled to fire while the gateway was down or being restarted), the gateway attempts to fire **all overdue jobs simultaneously** on startup. This overwhelms the gateway process and makes it completely unresponsive — the UI shows no cron jobs, `openclaw cron list` times out after 30s, and the WebSocket endpoint stops responding to cron-related requests.

Other gateway functions (e.g., `openclaw status`, `sessions.list` from UI) continue to work, suggesting the cron subsystem specifically is blocked.

## Steps to Reproduce

1. Set up multiple cron jobs with `nextRunAtMs` state values
2. Stop the gateway (or let it crash during a cron run)
3. Wait until several cron jobs become overdue (their `nextRunAtMs` is in the past)
4. Restart the gateway
5. Immediately try `openclaw cron list` or check the UI → times out / shows no cron jobs

## Expected Behavior

The gateway should either:
- **Stagger overdue jobs** — fire them one at a time with a configurable delay between each, rather than all at once
- **Skip overdue jobs** — detect that the scheduled time has passed and advance `nextRunAtMs` to the next occurrence based on the cron expression
- **Rate-limit concurrent cron executions** — enforce a maximum number of simultaneous cron sessions (ideally configurable, default 1)

## Actual Behavior

- All overdue cron jobs fire simultaneously on startup
- The gateway process (Node.js, ~430MB RSS) becomes completely unresponsive to cron-related WebSocket requests
- `openclaw cron list` returns `Error: gateway timeout after 30000ms`
- UI shows no cron jobs
- Gateway logs show `shutdown timed out; exiting without full cleanup` on subsequent restart attempts
- The only fix is to manually edit `jobs.json` to push all `nextRunAtMs` values into the future, then restart

## Workaround

Before restarting the gateway, push all overdue `nextRunAtMs` values into the future:

```python
import json
from datetime import datetime, timezone, timedelta

with open('~/.openclaw/cron/jobs.json') as f:
    data = json.load(f)

now = datetime.now(timezone.utc)
min_ms = int((now + timedelta(minutes=10)).timestamp() * 1000)

for job in data['jobs']:
    nrm = job.get('state', {}).get('nextRunAtMs', 0)
    if nrm < min_ms:
        job['state']['nextRunAtMs'] = min_ms

with open('~/.openclaw/cron/jobs.json', 'w') as f:
    json.dump(data, f, indent=2)
```

Then restart the gateway.

## Environment

- **OpenClaw version:** 2026.2.15
- **Node.js:** 22.17.1
- **OS:** Ubuntu 24.04 (Linux 6.8.0-94-generic x64)
- **Cron jobs:** 45 jobs configured, 10 were overdue at time of restart
- **Gateway config:** local loopback, single instance

### PR DESCRIPTION
**Pull request by rexlunae**
When the gateway restarts with many overdue cron jobs, they are now executed with staggered delays to prevent overwhelming the gateway.

- Add missedJobStaggerMs config (default 5s between jobs)
- Add maxMissedJobsPerRestart limit (default 5 jobs immediately)
- Prioritize most overdue jobs by sorting by nextRunAtMs
- Reschedule deferred jobs to fire gradually via normal timer

Fixes #18892

## Summary

Describe the problem and fix in 2–5 bullets:

- Problem:
- Why it matters:
- What changed:
- What did NOT change (scope boundary):

## Change Type (select all)

- [ ] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Docs
- [ ] Security hardening
- [ ] Chore/infra

## Scope (select all touched areas)

- [ ] Gateway / orchestration
- [ ] Skills / tool execution
- [ ] Auth / tokens
- [ ] Memory / storage
- [ ] Integrations
- [ ] API / contracts
- [ ] UI / DX
- [ ] CI/CD / infra

## Linked Issue/PR

- Closes #
- Related #

## User-visible / Behavior Changes

List user-visible changes (including defaults/config).  
If none, write `None`.

## Security Impact (required)

- New permissions/capabilities? (`Yes/No`)
- Secrets/tokens handling changed? (`Yes/No`)
- New/changed network calls? (`Yes/No`)
- Command/tool execution surface changed? (`Yes/No`)
- Data access scope changed? (`Yes/No`)
- If any `Yes`, explain risk + mitigation:

### Environment

- OS:
- Runtime/container:
- Model/provider:
- Integration/channel (if any):
- Relevant config (redacted):

### Steps

1.
2.
3.

### Expected

-

### Actual

-

## Evidence

Attach at least one:

- [ ] Failing test/log before + passing after
- [ ] Trace/log snippets
- [ ] Screenshot/recording
- [ ] Perf numbers (if relevant)

## Human Verification (required)

What you personally verified (not just CI), and how:

- Verified scenarios:
- Edge cases checked:
- What you did **not** verify:

## Compatibility / Migration

- Backward compatible? (`Yes/No`)
- Config/env changes? (`Yes/No`)
- Migration needed? (`Yes/No`)
- If yes, exact upgrade steps:

## Failure Recovery (if this breaks)

- How to disable/revert this change quickly:
- Files/config to restore:
- Known bad symptoms reviewers should watch for:

## Risks and Mitigations

List only real risks for this PR. Add/remove entries as needed. If none, write `None`.

- Risk:
  - Mitigation:

<h3>Greptile Summary</h3>

This PR addresses #18892 by staggering the execution of missed cron jobs when the gateway restarts with many overdue jobs. Previously, all missed jobs fired simultaneously, potentially overwhelming the gateway.

- Adds `missedJobStaggerMs` (default 5s) and `maxMissedJobsPerRestart` (default 5) as configurable options on `CronServiceDeps`
- Sorts missed jobs by `nextRunAtMs` (most overdue first), splits into immediate and deferred batches
- Immediate batch runs sequentially with stagger delays between executions; deferred batch gets rescheduled to staggered future `nextRunAtMs` values picked up by the normal timer
- The stagger scheduling is safe with respect to the `locked()` mechanism and `recomputeNextRuns` (which preserves future `nextRunAtMs` values)
- **Issue**: deferred job stagger offsets start at `staggerMs` instead of `maxImmediate * staggerMs`, so the first deferred jobs will be past-due by the time `armTimer` runs (after the immediate batch completes), causing them to fire back-to-back without the intended staggering

<h3>Confidence Score: 3/5</h3>

- The PR is safe to merge but the deferred job stagger timing has an overlap issue that reduces its effectiveness under default settings.
- The overall approach is sound and well-structured — sorting by overdue priority, splitting into immediate/deferred batches, and leveraging the existing timer mechanism for deferred execution. However, the deferred stagger offset calculation starts too early (at `staggerMs` from `now`), meaning the first several deferred jobs will be past-due by the time `armTimer` runs after the immediate batch completes, causing them to fire back-to-back and partially defeating the stagger purpose. The fix is straightforward (start offset at `maxImmediate * staggerMs`).
- `src/cron/service/timer.ts` — the deferred job stagger offset calculation in `runMissedJobs` needs adjustment to account for immediate batch execution time.

<sub>Last reviewed commit: eabeee0</sub>

<sub>(3/5) Reply to the agent's comments like "Can you suggest a fix for this @greptileai?" or ask follow-up questions!</sub>

### CODE REVIEW

File: src/cron/service/timer.ts [hunk 1]
```diff
@@ -413,13 +428,57 @@ export async function runMissedJobs(
...
+
+  if (immediate.length > 0) {
+    state.deps.log.info(
+      { count: immediate.length, jobIds: immediate.map((j) => j.id) },
       "cron: running missed jobs after restart",
     );
-    for (const job of missed) {
-      await executeJob(state, job, now, { forced: false });
+
+    // Run immediate jobs with stagger delays between them
```
Comment (ImLukeF) [inline src/cron/service/timer.ts]: This changes restart behavior more than the PR description suggests: `CronService.start()` awaits `runMissedJobs()` before it can `armTimer()` and finish startup (`src/cron/service/ops.ts:30-52`), and `runMissedJobs()` now does real `setTimeout` sleeps between the "immediate" jobs. With the default `maxMissedJobsPerRestart=5` / `missedJobStaggerMs=5000`, a restart with 5 missed jobs can now block cron startup for ~20 seconds while holding the cron lock. That seems like a regression for restart responsiveness, and it showed up locally when I tried to run the new targeted test: `pnpm exec vitest run src/cron/service.missed-jobs-stagger.test.ts` just sat waiting because `cron.start()` is now timer-driven under fake timers. I think the staggering needs to happen by rescheduling `nextRunAtMs` (or otherwise outside the startup await path), rather than sleeping inside `start()`.
