### PR TITLE
fix(macos): respect gateway.controlUi.basePath in Dashboard URL

### LINKED ISSUE #15743: [Bug]: macOS app “Open Dashboard” ignores gateway.controlUi.basePath and opens /?token=... (404)
## Summary

On macOS app 2026.2.12, clicking Open Dashboard opens:
http://127.0.0.1:18789/?token=...
which returns 404, instead of respecting configured UI base path /ui.

Clicking Open Dashboard doesn't open the Dashboard

## Steps to reproduce

1. Set a Tailscale URL ending in /ui/
2. Click Open Dashboard in the macOS app's dropdown menu
3. Watch the Dashboard fail to open

## Expected behavior

Open Dashboard should launch:
http://127.0.0.1:18789/ui/?token=...
(or equivalent /ui/... route)

## Actual behavior

App launches root URL:
http://127.0.0.1:18789/?token=... → 404

## Environment

- OpenClaw app: 2026.2.12
- macOS 15. 7.4
- Gateway mode: local, bind loopback
- Config: gateway.controlUi.basePath = "/ui"
- Auth mode: token
- Tailscale Serve enabled
- Install method (pnpm/npx/docker/etc): curl -fsSL https://openclaw.ai/install.sh | bash

## Logs or screenshots

Paste relevant logs or add screenshots (redact secrets).

### PR DESCRIPTION
**Pull request by Shuai-DaiDai**
## Problem

The macOS app ignores the configured gateway.controlUi.basePath when opening the Dashboard, always using '/' which results in 404 when a custom basePath is set.

## Solution

- Added gatewayControlUiBasePath() method to read the config
- Updated dashboardURL() to use the configured basePath
- Properly formats path with leading/trailing slashes

Fixes #15743

<h2>Greptile Overview</h2>

<h3>Greptile Summary</h3>

This PR fixes the macOS menu bar app’s “Open Dashboard” URL generation to respect `gateway.controlUi.basePath` instead of always opening `/`, by adding a config reader (`OpenClawConfigFile.gatewayControlUiBasePath()`) and wiring it into `GatewayEndpointStore.dashboardURL()`.

It also includes unrelated documentation tweaks (compaction config text and GitHub skill GraphQL guidance) and expands Moonshot model provider defaults (correcting the default model id and adding additional model variants).

<h3>Confidence Score: 3/5</h3>

- This PR is mostly safe, but has at least one behavior issue that can break remote dashboard URLs and one doc inconsistency.
- The macOS basePath fix is straightforward for local gateways, but `dashboardURL()` now reads basePath exclusively from the local config file even when connected to a remote gateway URL, which can produce incorrect links in remote/direct modes. Additionally, the compaction doc change appears to reference a different config filename than the rest of the repo, which will mislead users.
- apps/macos/Sources/OpenClaw/GatewayEndpointStore.swift, docs/concepts/compaction.md

<sub>Last reviewed commit: 28d7741</sub>

<sub>(5/5) You can turn off certain types of comments like style [here](https://app.greptile.com/review/github)!</sub>

### CODE REVIEW

File: src/agents/models-config.providers.ts [hunk 1]
```diff
@@ -465,13 +467,40 @@ function buildMoonshotProvider(): ProviderConfig {
     models: [
       {
         id: MOONSHOT_DEFAULT_MODEL_ID,
-        name: "Kimi K2.5",
+        name: "Kimi K2 (0905 Preview)",
```
Comment (steipete) [inline src/agents/models-config.providers.ts]: this seems unrelated... causing more work
